[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
name    = "relay-westend-client"
version = "0.1.0"

[dependencies]
codec                  = { package = "parity-scale-codec", version = "2.0.0" }
headers-relay          = { path = "../headers" }
relay-substrate-client = { path = "../client-substrate" }
relay-utils            = { path = "../utils" }

# Bridge dependencies

bp-westend = { path = "../../primitives/chain-westend" }

# Substrate Dependencies

frame-support              = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.2" }
frame-system               = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.2" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.2" }
sp-core                    = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.2" }
sp-keyring                 = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.2" }
sp-runtime                 = { git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.2" }
