[package]
name = "millau-bridge-node"
description = "Substrate node compatible with Millau runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-bridges-common/"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
jsonrpc-core = "15.1.0"
structopt = "0.3.21"

# Bridge dependencies

bp-messages = { path = "../../../primitives/messages" }
bp-millau= { path = "../../../primitives/chain-millau" }
bp-runtime = { path = "../../../primitives/runtime" }
millau-runtime = { path = "../runtime" }
pallet-bridge-messages = { path = "../../../modules/messages" }

# Substrate Dependencies

frame-benchmarking = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
frame-benchmarking-cli = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
node-inspect = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
pallet-transaction-payment-rpc = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-basic-authorship = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-cli = { git = "https://github.com/darwinia-network/substrate", branch = "s2s", features = ["wasmtime"] }
sc-client-api = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-consensus = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-consensus-aura = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-executor = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-finality-grandpa = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-finality-grandpa-rpc = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-keystore = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-rpc = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-service = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-telemetry = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-transaction-pool = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-consensus = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-consensus-aura = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-core = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-inherents = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
substrate-frame-rpc-system = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }

[build-dependencies]
substrate-build-script-utils = "3.0.0"
frame-benchmarking-cli = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }

[features]
default = []

# TODO: https://github.com/paritytech/parity-bridges-common/issues/390
# I've left the feature flag here to test our CI configuration
runtime-benchmarks = [
	# "millau-runtime/runtime-benchmarks",
]
