[package]
name = "relay-substrate-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
async-std = "1.6.5"
async-trait = "0.1.40"
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpsee-proc-macros = "=0.2.0-alpha.5"
jsonrpsee-ws-client = "=0.2.0-alpha.5"
log = "0.4.11"
num-traits = "0.2"
rand = "0.7"

# Bridge dependencies

bp-header-chain = { path = "../../primitives/header-chain" }
bp-messages = { path = "../../primitives/messages" }
bp-runtime = { path = "../../primitives/runtime" }
finality-relay = { path = "../finality" }
headers-relay = { path = "../headers" }
relay-utils = { path = "../utils" }

# Substrate Dependencies

frame-support = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
frame-system = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
pallet-balances = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-rpc-api = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-core = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-finality-grandpa = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-storage = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-std = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-trie = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-version = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }

#[dev-dependencies]
futures = "0.3.7"
